-- Seed data for accomplishment_activity table
INSERT INTO
    accomplishment_activity (
        id,
        accomplishment_annual_plan_id,
        activity,
        input_type,
        performance_indicator,
        annual_target,
        q1_accomplishment,
        q2_accomplishment,
        q3_accomplishment,
        q4_accomplishment,
        total,
        accomplishment_rate,
        responsible_officer_unit,
        remarks,
        position
    )
VALUES
    -- Activities for Instruction Annual Plan (2 activities)
    (
        gen_random_uuid (),
        'b5eb9a6d-1c2f-4fab-8071-ae5a5f5c6e01',
        'Review and update curriculum content',
        'percentage',
        'Percentage of courses reviewed and updated',
        '100%',
        '25%',
        '50%',
        '75%',
        '100%',
        '100%',
        '100%',
        'Academic Affairs Committee',
        'Successfully completed all course reviews',
        1
    ),
    (
        gen_random_uuid (),
        'b5eb9a6d-1c2f-4fab-8071-ae5a5f5c6e01',
        'Implement outcomes-based education frameworks',
        'number',
        'Number of programs implementing OBE',
        '10',
        '3',
        '5',
        '8',
        '10',
        '10',
        '100%',
        'Program Heads',
        'Full implementation achieved',
        2
    ),
    -- Activities for Research Annual Plans
    -- First Research Plan (1 activity)
    (
        gen_random_uuid (),
        'c6eb9a6d-1c2f-4fab-8071-ae5a5f5c6e02',
        'Submit research papers to indexed journals',
        'number',
        'Number of papers submitted',
        '20',
        '5',
        '10',
        '15',
        '18',
        '18',
        '90%',
        'Research Department',
        'Nearly achieved target',
        1
    ),
    -- Second Research Plan (3 activities)
    (
        gen_random_uuid (),
        'c7eb9a6d-1c2f-4fab-8071-ae5a5f5c6e03',
        'Organize industry partner meetings',
        'number',
        'Number of partnership meetings conducted',
        '12',
        '3',
        '6',
        '9',
        '12',
        '12',
        '100%',
        'Research Coordination Office',
        'All planned meetings conducted',
        1
    ),
    (
        gen_random_uuid (),
        'c7eb9a6d-1c2f-4fab-8071-ae5a5f5c6e03',
        'Sign MOUs with industry partners',
        'number',
        'Number of MOUs signed',
        '5',
        '1',
        '2',
        '4',
        '5',
        '5',
        '100%',
        'Research Coordination Office',
        'All target MOUs signed',
        2
    ),
    (
        gen_random_uuid (),
        'c7eb9a6d-1c2f-4fab-8071-ae5a5f5c6e03',
        'Conduct joint research projects',
        'number',
        'Number of joint projects initiated',
        '3',
        '0',
        '1',
        '2',
        '3',
        '3',
        '100%',
        'Research Teams',
        'Successfully initiated all planned projects',
        3
    ),
    -- Third Research Plan (2 activities)
    (
        gen_random_uuid (),
        'c8eb9a6d-1c2f-4fab-8071-ae5a5f5c6e04',
        'Conduct research methodology workshops',
        'number',
        'Number of workshops conducted',
        '8',
        '2',
        '4',
        '6',
        '8',
        '8',
        '100%',
        'Research Development Unit',
        'All workshops successfully conducted',
        1
    ),
    (
        gen_random_uuid (),
        'c8eb9a6d-1c2f-4fab-8071-ae5a5f5c6e04',
        'Provide research mentoring sessions',
        'number',
        'Number of mentoring sessions conducted',
        '24',
        '6',
        '12',
        '18',
        '24',
        '24',
        '100%',
        'Senior Researchers',
        'Completed all planned sessions',
        2
    ),
    -- Management and Governance Plans (varying activities per plan)
    -- First Plan (4 activities)
    (
        gen_random_uuid (),
        'd1eb9a6d-1c2f-4fab-8071-ae5a5f5c6e05',
        'Develop strategic plans',
        'number',
        'Number of strategic plans developed',
        '5',
        '2',
        '3',
        '4',
        '5',
        '5',
        '100%',
        'Strategic Planning Committee',
        'All plans completed',
        1
    ),
    (
        gen_random_uuid (),
        'd1eb9a6d-1c2f-4fab-8071-ae5a5f5c6e05',
        'Conduct stakeholder consultations',
        'number',
        'Number of consultation meetings',
        '12',
        '3',
        '6',
        '9',
        '12',
        '12',
        '100%',
        'Administrative Office',
        'Successfully engaged all stakeholders',
        2
    ),
    (
        gen_random_uuid (),
        'd1eb9a6d-1c2f-4fab-8071-ae5a5f5c6e05',
        'Draft implementation guidelines',
        'percentage',
        'Percentage of guidelines completed',
        '100%',
        '25%',
        '50%',
        '75%',
        '100%',
        '100%',
        '100%',
        'Policy Committee',
        'All guidelines completed and approved',
        3
    ),
    (
        gen_random_uuid (),
        'd1eb9a6d-1c2f-4fab-8071-ae5a5f5c6e05',
        'Monitor implementation progress',
        'percentage',
        'Percentage of implementation monitored',
        '100%',
        '25%',
        '50%',
        '75%',
        '100%',
        '100%',
        '100%',
        'Monitoring Team',
        'Comprehensive monitoring completed',
        4
    ),
    -- Second Plan (1 activity)
    (
        gen_random_uuid (),
        'd2eb9a6d-1c2f-4fab-8071-ae5a5f5c6e06',
        'Streamline administrative processes',
        'number',
        'Number of processes optimized',
        '10',
        '3',
        '5',
        '8',
        '10',
        '10',
        '100%',
        'Process Improvement Team',
        'All target processes optimized',
        1
    ),
    -- Extension Plans (2 activities)
    (
        gen_random_uuid (),
        'e1eb9a6d-1c2f-4fab-8071-ae5a5f5c6e09',
        'Implement community literacy program',
        'number',
        'Number of beneficiaries',
        '500',
        '125',
        '250',
        '375',
        '500',
        '500',
        '100%',
        'Community Extension Office',
        'Target beneficiaries reached',
        1
    ),
    (
        gen_random_uuid (),
        'e1eb9a6d-1c2f-4fab-8071-ae5a5f5c6e09',
        'Conduct health awareness campaigns',
        'number',
        'Number of campaigns conducted',
        '12',
        '3',
        '6',
        '9',
        '12',
        '12',
        '100%',
        'Health Services Unit',
        'All planned campaigns completed',
        2
    ),
    -- Linkages Activities (1 activity)
    (
        gen_random_uuid (),
        'f1eb9a6d-1c2f-4fab-8071-ae5a5f5c6e11',
        'Establish international partnerships',
        'number',
        'Number of partnerships established',
        '5',
        '1',
        '2',
        '4',
        '5',
        '5',
        '100%',
        'International Relations Office',
        'All target partnerships established',
        1
    ),
    -- Student Services Activities (3 activities)
    (
        gen_random_uuid (),
        'a1eb9a6d-1c2f-4fab-8071-ae5a5f5c6e14',
        'Enhance counseling services',
        'number',
        'Number of students served',
        '1000',
        '250',
        '500',
        '750',
        '1000',
        '1000',
        '100%',
        'Guidance Office',
        'Target number of students reached',
        1
    ),
    (
        gen_random_uuid (),
        'a1eb9a6d-1c2f-4fab-8071-ae5a5f5c6e14',
        'Implement mental health programs',
        'number',
        'Number of programs implemented',
        '8',
        '2',
        '4',
        '6',
        '8',
        '8',
        '100%',
        'Health Services',
        'All programs successfully implemented',
        2
    ),
    (
        gen_random_uuid (),
        'a1eb9a6d-1c2f-4fab-8071-ae5a5f5c6e14',
        'Conduct student wellness workshops',
        'number',
        'Number of workshops conducted',
        '12',
        '3',
        '6',
        '9',
        '12',
        '12',
        '100%',
        'Student Affairs Office',
        'All planned workshops conducted',
        3
    ),
    -- Alumni Relations Activities (2 activities)
    (
        gen_random_uuid (),
        'b1eb9a6d-1c2f-4fab-8071-ae5a5f5c6e16',
        'Organize alumni homecoming events',
        'number',
        'Number of events organized',
        '4',
        '1',
        '2',
        '3',
        '4',
        '4',
        '100%',
        'Alumni Affairs Office',
        'All events successfully conducted',
        1
    ),
    (
        gen_random_uuid (),
        'b1eb9a6d-1c2f-4fab-8071-ae5a5f5c6e16',
        'Update alumni database',
        'percentage',
        'Percentage of alumni records updated',
        '100%',
        '25%',
        '50%',
        '75%',
        '100%',
        '100%',
        '100%',
        'Alumni Relations',
        'Database fully updated',
        2
    );