-- Create technical_extension_service table
CREATE TABLE technical_extension_service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ipcr_id UUID NOT NULL REFERENCES ipcr(id) ON DELETE CASCADE,
    success_indicators TEXT NOT NULL,
    actual_accomplishments TEXT,
    evidence_img_urls TEXT[] DEFAULT ARRAY[]::TEXT[],
    rating_q NUMERIC(3,2) NOT NULL CHECK (rating_q BETWEEN 1.00 AND 5.00),
    rating_e NUMERIC(3,2) NOT NULL CHECK (rating_e BETWEEN 1.00 AND 5.00),
    rating_t NUMERIC(3,2) NOT NULL CHECK (rating_t BETWEEN 1.00 AND 5.00),
    rating_a NUMERIC(3,2) NOT NULL CHECK (rating_a BETWEEN 1.00 AND 5.00),
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create index for foreign key
CREATE INDEX idx_technical_extension_service_ipcr_id ON technical_extension_service(ipcr_id);

-- Add updated_at trigger
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON technical_extension_service
    FOR EACH ROW
    EXECUTE FUNCTION fn_set_updated_at();

-- Enable Row Level Security
ALTER TABLE technical_extension_service ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can perform all operations on their own technical_extension service"
    ON technical_extension_service
    TO authenticated
    USING (ipcr_id IN (
        SELECT id FROM ipcr WHERE owner_id = auth.uid()
    ));