-- create table
CREATE TABLE employee_status (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
   type VARCHAR(100) NOT NULL UNIQUE,
   created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
   updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- Add updated_at trigger
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON employee_status
    FOR EACH ROW
    EXECUTE FUNCTION fn_set_updated_at();
