-- Create support_function table
CREATE TABLE support_function (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ipcr_id UUID NOT NULL REFERENCES ipcr(id) ON DELETE CASCADE,
    support_function_header_id UUID NOT NULL REFERENCES support_function_header(id) ON DELETE CASCADE,
    success_indicators TEXT NOT NULL,
    actual_accomplishments TEXT,
    evidence_img_urls TEXT[] DEFAULT ARRAY[]::TEXT[],
    rating_q NUMERIC(3,2) NOT NULL CHECK (rating_q BETWEEN 1.00 AND 5.00),
    rating_e NUMERIC(3,2) NOT NULL CHECK (rating_e BETWEEN 1.00 AND 5.00),
    rating_t NUMERIC(3,2) NOT NULL CHECK (rating_t BETWEEN 1.00 AND 5.00),
    rating_a NUMERIC(3,2) NOT NULL CHECK (rating_a BETWEEN 1.00 AND 5.00),
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT max_evidence_imgs CHECK (array_length(evidence_img_urls, 1) <= 3)
);

-- Create indexes for foreign keys
CREATE INDEX idx_support_function_ipcr_id ON support_function(ipcr_id);
CREATE INDEX idx_support_function_header_id ON support_function(support_function_header_id);

-- Add updated_at trigger
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON support_function
    FOR EACH ROW
    EXECUTE FUNCTION fn_set_updated_at();

-- Enable Row Level Security
ALTER TABLE support_function ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can perform all operations on their own support functions"
    ON support_function
    TO authenticated
    USING (ipcr_id IN (
        SELECT id FROM ipcr WHERE owner_id = auth.uid()
    ));