-- Create administrative_designation table
CREATE TABLE administrative_designation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ipcr_id UUID NOT NULL REFERENCES ipcr(id) ON DELETE CASCADE,
    success_indicators TEXT NOT NULL,
    actual_accomplishments TEXT,
    evidence_img_urls TEXT[] DEFAULT ARRAY[]::TEXT[],
    rating_q NUMERIC(3,2) NOT NULL CHECK (rating_q BETWEEN 1.00 AND 5.00),
    rating_e NUMERIC(3,2) NOT NULL CHECK (rating_e BETWEEN 1.00 AND 5.00),
    rating_t NUMERIC(3,2) NOT NULL CHECK (rating_t BETWEEN 1.00 AND 5.00),
    rating_a NUMERIC(3,2) NOT NULL CHECK (rating_a BETWEEN 1.00 AND 5.00),
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT max_evidence_imgs CHECK (array_length(evidence_img_urls, 1) <= 3)
);

-- Create index for foreign key
CREATE INDEX idx_administrative_designation_ipcr_id ON administrative_designation(ipcr_id);

-- Add updated_at trigger
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON administrative_designation
    FOR EACH ROW
    EXECUTE FUNCTION fn_set_updated_at();

-- Enable Row Level Security
ALTER TABLE administrative_designation ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can perform all operations on their own administrative designation"
    ON administrative_designation
    TO authenticated
    USING (ipcr_id IN (
        SELECT id FROM ipcr WHERE owner_id = auth.uid()
    ));