/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IPFSFileTracker {
  export type FileReferenceStruct = {
    cid: string;
    action: BigNumberish;
    fileType: BigNumberish;
    fileName: string;
    timestamp: BigNumberish;
    blockHash: BytesLike;
    exists: boolean;
  };

  export type FileReferenceStructOutput = [
    cid: string,
    action: bigint,
    fileType: bigint,
    fileName: string,
    timestamp: bigint,
    blockHash: string,
    exists: boolean
  ] & {
    cid: string;
    action: bigint;
    fileType: bigint;
    fileName: string;
    timestamp: bigint;
    blockHash: string;
    exists: boolean;
  };
}

export interface IPFSFileTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addFileReference"
      | "fileExists"
      | "getCurrentBlockHash"
      | "getFileReference"
      | "getOwner"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FileReferenceAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addFileReference",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "fileExists", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getCurrentBlockHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFileReference",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getOwner", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addFileReference",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fileExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentBlockHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFileReference",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
}

export namespace FileReferenceAddedEvent {
  export type InputTuple = [
    action: BigNumberish,
    cid: string,
    fileType: BigNumberish,
    fileName: string,
    timestamp: BigNumberish,
    blockHash: BytesLike
  ];
  export type OutputTuple = [
    action: bigint,
    cid: string,
    fileType: bigint,
    fileName: string,
    timestamp: bigint,
    blockHash: string
  ];
  export interface OutputObject {
    action: bigint;
    cid: string;
    fileType: bigint;
    fileName: string;
    timestamp: bigint;
    blockHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPFSFileTracker extends BaseContract {
  connect(runner?: ContractRunner | null): IPFSFileTracker;
  waitForDeployment(): Promise<this>;

  interface: IPFSFileTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addFileReference: TypedContractMethod<
    [_cid: string, _fileType: BigNumberish, _fileName: string],
    [void],
    "nonpayable"
  >;

  fileExists: TypedContractMethod<[_cid: string], [boolean], "view">;

  getCurrentBlockHash: TypedContractMethod<[], [string], "view">;

  getFileReference: TypedContractMethod<
    [_cid: string],
    [IPFSFileTracker.FileReferenceStructOutput],
    "view"
  >;

  getOwner: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addFileReference"
  ): TypedContractMethod<
    [_cid: string, _fileType: BigNumberish, _fileName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fileExists"
  ): TypedContractMethod<[_cid: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "getCurrentBlockHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getFileReference"
  ): TypedContractMethod<
    [_cid: string],
    [IPFSFileTracker.FileReferenceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwner"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FileReferenceAdded"
  ): TypedContractEvent<
    FileReferenceAddedEvent.InputTuple,
    FileReferenceAddedEvent.OutputTuple,
    FileReferenceAddedEvent.OutputObject
  >;

  filters: {
    "FileReferenceAdded(uint8,string,uint8,string,uint256,bytes32)": TypedContractEvent<
      FileReferenceAddedEvent.InputTuple,
      FileReferenceAddedEvent.OutputTuple,
      FileReferenceAddedEvent.OutputObject
    >;
    FileReferenceAdded: TypedContractEvent<
      FileReferenceAddedEvent.InputTuple,
      FileReferenceAddedEvent.OutputTuple,
      FileReferenceAddedEvent.OutputObject
    >;
  };
}
